general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    layout = dwindle
    col.active_border = rgb(e63946)
    col.inactive_border = rgb(1a1a2e)
}
decoration {
    rounding = 2
    active_opacity = 1.0
    blur {
        enabled = true
        size = 3
        passes = 2
    }
    shadow {
        enabled = true
        range = 12
    }
}
