general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
    col.active_border = rgb(c97a9e)
    col.inactive_border = rgb(1a2433)
}
decoration {
    rounding = 6
    active_opacity = 0.98
    blur {
        enabled = true
        size = 5
        passes = 2
    }
    shadow {
        enabled = true
        range = 25
    }
}
