general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    layout = dwindle
    col.active_border = rgb(5e81ac)
    col.inactive_border = rgb(3b4252)
}
decoration {
    rounding = 6
    active_opacity = 1.0
    blur {
        enabled = true
        size = 5
        passes = 2
    }
    shadow {
        enabled = true
        range = 15
    }
}
