general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
    col.active_border = rgb(ff2d95)
    col.inactive_border = rgb(2a0a45)
}
decoration {
    rounding = 10
    active_opacity = 1.0
    blur {
        enabled = true
        size = 6
        passes = 3
    }
    shadow {
        enabled = true
        range = 30
    }
}
