general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    layout = dwindle
    col.active_border = rgb(8bc34a)
    col.inactive_border = rgb(2a2520)
}
decoration {
    rounding = 12
    active_opacity = 0.98
    blur {
        enabled = true
        size = 8
        passes = 3
    }
}
