exec-once = waybar
exec-once = mako
exec-once = swaybg -i /usr/share/hyprwave/wallpapers/default.png -m fill
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = hypridle
exec-once = nm-applet --indicator
exec-once = cliphist
