background {
    monitor =
    path = /usr/share/hyprwave/wallpapers/default.png
    blur_passes = 3
    blur_size = 10
    brightness = 0.6
    contrast = 0.9
    color = rgba(11, 1, 33, 1.0)
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgb(ff2d95)
    inner_color = rgb(11, 1, 33)
    font_color = rgb(e0e0ff)
    fade_on_empty = true
    placeholder_text = <i>access granted...</i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = H Y P R W A V E
    color = rgb(00f0ff)
    font_size = 56
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(ff2d95)
    font_size = 28
    font_family = JetBrains Mono
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = <span foreground="#b967ff">▂ ▄ ▅ ▇ █ ▇ ▅ ▄ ▂</span>
    font_size = 18
    font_family = JetBrains Mono
    position = 0, -45
    halign = center
    valign = center
}
